import "./globals.scss";
import { Inter } from "next/font/google";
import Header from "./_layout/Header";
import Footer from "./_layout/Footer";
import { Providers } from "./_layout/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "the zcd portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gradient-radial from-black to-white shadow-lg border-2 border-gray-300 rounded-lg p-4">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
